# Generated by Django 5.0.6 on 2026-08-13 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Метаданные (JSONB)'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Ожидает обработки'), ('PROCESSED', 'Обработано'), ('FAILED', 'Ошибка обработки')], db_index=True, default='PENDING', max_length=20, verbose_name='Статус обработки'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='target_content_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип целевого объекта'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='target_object_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID целевого объекта'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип контента'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID объекта'),
        ),
    ]
