# Generated by Django 5.0.6 on 2026-08-13 05:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название этапа')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('active', 'В работе'), ('completed', 'Завершен')], default='active', max_length=20, verbose_name='Статус')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Этап проекта',
                'verbose_name_plural': 'Этапы проектов',
                'db_table': 'stages',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название задачи')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workflow.stage', verbose_name='Этап НИР')),
            ],
            options={
                'verbose_name': 'Задача НИР',
                'verbose_name_plural': 'Задачи НИР',
                'db_table': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название выхода')),
                ('output_type', models.CharField(max_length=100, verbose_name='Тип выхода (Отчет/Статья/Патент)')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('submitted', 'На проверке'), ('returned', 'На доработке'), ('completed', 'Выполнен')], default='new', max_length=20, verbose_name='Статус')),
                ('deadline', models.DateField(verbose_name='Срок сдачи')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='workflow.task', verbose_name='Задача НИР')),
            ],
            options={
                'verbose_name': 'Выход (Результат)',
                'verbose_name_plural': 'Выходы (Результаты)',
                'db_table': 'outputs',
            },
        ),
    ]
