services:
  # СЕРВИС БАЗЫ ДАННЫХ POSTGRESQL
  db:
    image: postgres:16-alpine
    container_name: system_v1_db
    # Берем пароли из скрытого файла .env
    env_file:
      - .env
    volumes:
      - .docker-data/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      # Заменил жесткие значения на переменные (на случай если в .env вы их поменяете)
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # СЕРВИС REDIS (БРОКЕР ДЛЯ CELERY БИТ И ОЧЕРЕДЕЙ)
  redis:
    image: redis:7-alpine
    container_name: system_v1_redis
    ports:
      - "6379:6379"

  # ОСНОВНОЕ DJANGO ПРИЛОЖЕНИЕ (БЭКЕНД И WEB)
  web:
    build: .
    container_name: system_v1_web
    # БОЕВОЙ СЕРВЕР: Вместо runserver используем Gunicorn
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --chdir /app/src
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./src:/app/src
      # Подключаем общие тома для статики
      - static_volume:/app/src/staticfiles
      - media_volume:/app/src/media
    # Убрали ports: "8000:8000". Теперь Django общается только внутри сети Docker.
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  # ВОРКЕР CELERY ДЛЯ ФОНОВЫХ ЗАДАЧ (УВЕДОМЛЕНИЯ, СРОКИ)
  celery_worker:
    build: .
    container_name: system_v1_celery
    command: celery -A src.config.celery worker --loglevel=info
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./src:/app/src
      - static_volume:/app/src/staticfiles
      - media_volume:/app/src/media
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  # БОЕВОЙ ВЕБ-СЕРВЕР NGINX (ОТДАЧА СТАТИКИ И МАРШРУТИЗАЦИЯ)
  nginx:
    image: nginx:1.25-alpine
    container_name: system_v1_nginx
    ports:
      - "80:80" # Открываем стандартный HTTP порт наружу
    volumes:
      # Подкидываем наш файл конфигурации
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # Подключаем общие тома, чтобы Nginx видел файлы Django
      - static_volume:/app/src/staticfiles
      - media_volume:/app/src/media
    depends_on:
      - web

# ОПРЕДЕЛЕНИЕ ОБЩИХ ТОМОВ (VOLUMES) ДЛЯ ВСЕХ КОНТЕЙНЕРОВ
volumes:
  static_volume:
  media_volume: