# Generated by Django 5.0.6 on 2026-08-13 05:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(verbose_name='Название проекта')),
                ('project_type', models.CharField(choices=[('tz', 'По техническому заданию'), ('grant', 'Грант'), ('contract', 'Договор / Контракт'), ('internal', 'Внутренний научный проект')], max_length=50, verbose_name='Тип проекта')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('planned', 'Запланирован'), ('in_progress', 'В работе'), ('review', 'На приемке'), ('completed', 'Завершен')], default='draft', max_length=20, verbose_name='Статус')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to='organization.employee', verbose_name='Руководитель проекта')),
                ('members', models.ManyToManyField(blank=True, related_name='projects', to='organization.employee', verbose_name='Участники проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'db_table': 'projects',
            },
        ),
    ]
