# Generated by Django 5.0.6 on 2026-09-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentmembership',
            options={},
        ),
        migrations.AddIndex(
            model_name='departmentmembership',
            index=models.Index(fields=['employee', 'department', 'is_primary'], name='department__employe_7f1cf5_idx'),
        ),
    ]
