# Generated by Django 5.0.6 on 2026-08-13 05:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_responsible', models.BooleanField(default=False, verbose_name='Ответственный исполнитель')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('department_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='organization.departmentmembership', verbose_name='Кадровая роль (Подразделение и должность)')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='organization.employee', verbose_name='Сотрудник')),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='workflow.output', verbose_name='Выход (Результат)')),
            ],
            options={
                'verbose_name': 'Назначение исполнителя',
                'verbose_name_plural': 'Назначения исполнителей',
                'db_table': 'assignments',
                'unique_together': {('output', 'employee', 'department_membership')},
            },
        ),
    ]
