# Generated by Django 5.0.6 on 2026-09-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
        ('organization', '0002_alter_departmentmembership_options_and_more'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['is_responsible'], name='assignments_is_resp_41a240_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['employee', 'output'], name='assignments_employe_51afcd_idx'),
        ),
    ]
